### ISSUE TITLE
Should not use `omitempty` with `Enabled`

### ISSUE THREAD

**Issue by paultyng** [paultyng/go-newrelic#2]
https://github.com/paultyng/go-newrelic/blob/37814ca9c24a7e5f9455c7e71a79b6732bab1912/api/types.go#L55

**Comment by paultyng** [comment]
Probably shouldn't really use it on  non-pointer types in general.

**Comment by sgsiebers** [comment]
@paultyng I just encountered this same issue while testing out https://github.com/terraform-providers/terraform-provider-newrelic/pull/53.  The problem also exists on the AlertNRQLCondition, and presumably others.  Using omitempty causes REST API calls to ignore a "false" configuration value.

Happy to submit a pull request to fix this.  Look for one soon.

**Comment by sgsiebers** [comment]
@paultyng  or @bridgetlane, I think this issue can be closed with the above PR merged and releases.
