### ISSUE TITLE
Add support for ApplicationDeployment delete

### ISSUE THREAD

**Issue by ericksoen** [paultyng/go-newrelic#64]
I noticed that [Deployments.go](https://github.com/paultyng/go-newrelic/blob/master/api/deployments.go) did not include the [Delete method](https://rpm.newrelic.com/api/explore/application_deployments/delete) referenced in the New Relic API documentation.

Would you be open to a PR to support that API behavior, or was it intentionally excluded for a reason?

**Comment by ctrombley** [comment]
Addressed in #66.
